matches:
  - trigger: ":hello"
    replace: Hola,

     Estamos contactando a los equipos con jugadores Nica para conocer sus planes de entreno y ver si hay huecos. Si nos responden por este medio o en el foro podremos acelerar las cosas.

     Por favor, indícanos
    	•	Entrenamiento actual
    	•	Semanas que durará
    	•	Próximo entreno y duración
    	•	Si tienen hueco y buscan algo en concreto

     Esto nos ayudará a armar un listado de granjas y [b]puede servirte también para formar tu equipo y proyecto[/b].

     ¡Gracias por el apoyo! 🚀⚽
